### PR TITLE
support multiValueQueryStringParameters

### PR DESCRIPTION
**Pull request by anthonyroach**
This PR is identical to https://github.com/dougmoscrop/serverless-http/pull/67
except this PR has tests.

### CODE REVIEW

**Comment by anthonyroach** [comment]
Credit goes to @jamesvillarrubia for the original PR. I copied his work and added tests as requested.

**Comment by anthonyroach** [comment]
This fixes #70

**Comment by anthonyroach** [comment]
@dougmoscrop any chance this can get merged and released soon? I'm trying to decide whether it is worth building and using my fork in the short term.

**Comment by dougmoscrop** [comment]
just FYI, npm pretty seamlessly suports this, you can just change the version in your package.json to `github:lifeomic#{sha}`

but I will try to release asap

**Comment by anthonyroach** [comment]
TIL, thanks for the tip!

**Pull request merged**
