### PR TITLE
fix: multi valued set-cookie & other headers

### PR DESCRIPTION
**Pull request by SachinShekhar**
API Gateway lambda proxy integration has special ways to deal with multi valued header which then gets translated to RFC standard adhering multiple separate headers. With event payload version 1.0, a `multiValueHeaders` array can be returned. With event payload version 2.0, a cookie array can be returned. This PR makes use of these features to replace existing hacks. A salute for creating [`set-cookie.json` file](https://github.com/dougmoscrop/serverless-http/blob/master/lib/provider/aws/set-cookie.json) (I literally laughed after seeing it), unfortunately it doesn't work with at least event payload version 2.0 despite it being in adherence with the standard.

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Thank you! I had just kicked myself for not getting around to this yet! Can you add a couple tests?

**Comment by SachinShekhar** [comment]
@dougmoscrop Done.

**Comment by vtrifonov** [comment]
This seems to be a breaking change for payload version 1.0 however. You cannot set more than one cookie there because of this change :(

**Comment by SachinShekhar** [comment]
@vtrifonov I don't think I touched the behavior of payload version 1.0. Did you test your setup with previous version of this library?

**Comment by vtrifonov** [comment]
yep, it works with 2.5.0, but doesn't work with 2.6.0. Only the first cookie is set because of this https://github.com/dougmoscrop/serverless-http/pull/168/files#diff-b9c5826a549f306864d42b1a4c2a137a3061fbd640ae6933149ace0cf8cfae59R13

**Comment by SachinShekhar** [comment]
@vtrifonov I rechecked the code changes. Multiple cookies are being returned via `multiValueHeaders` which is adherence with [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format).

Please, log the response before returning it in Lambda & paste it here. Also, show me what headers web browser is receiving.

**Pull request merged**
