### PR TITLE
Add support for LoopBack 4

### PR DESCRIPTION
**Pull request by joe-niland**
Added detection of LoopBack 4 app main function to getFramework()

### CODE REVIEW

**Comment by dougmoscrop** [comment]
seems good, can you add a test that just does hello world?

**Comment by joe-niland** [comment]
Sure - i'm trying to figure out which function I need to hook into to create the app for the test

**Comment by joe-niland** [comment]
@dougmoscrop how's that for a basic test? I'm a LoopBack novice so I am not sure if that would be considered thorough by the project maintainers, but there it is anyway.

**Comment by dougmoscrop** [comment]
Looks good, thanks for your contribution!

**Pull request merged**
