### PR TITLE
fix originalUrl

### PR DESCRIPTION
**Pull request by adrai**
I compared that to the behavior of aws-serverless-express.

### CODE REVIEW

**Comment by adrai** [comment]
any feedback?

**Comment by dougmoscrop** [comment]
Well the tests fail - I don't mind working from here as a starting point but I just don't have the time at the moment.

**Comment by adrai** [comment]
You're right, I adapted the tests

**Comment by adrai** [comment]
no need to hurry... adapted my code to work with req.url in the meantime

**Comment by dougmoscrop** [comment]
some background on .requestContext.path - https://github.com/dougmoscrop/serverless-http/pull/42#issuecomment-376981255

I'm not sure about any of this, we're using API gateway behind a custom domain for all things.

**Pull request merged**
