### PR TITLE
#35 Include baseUrl in request object

### PR DESCRIPTION
**Pull request by XuluWarrior**

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Thanks for this.

Are there any concerns with baseUrl/originalUrl conflicting with what some frameworks expect to be there or with what properties they add?

Can you give me some sample values from your testing that showed what each property was set to (with custom domain, etc.)?

**Comment by dougmoscrop** [comment]
also the easiest way for me to understand what's happening would be to add a test or two.

koa and express are what I "officially" support here, I need to look at their internal use of the req object to make sure these extra properties aren't going to confuse anything.

**Comment by XuluWarrior** [comment]
Sorry for not getting back to you on this.  I've just started a new job, so have been rather busy.
It is possible that I might be able to look at this this weekend.  But if not, it might be a while till I next get a chance.

**Comment by dougmoscrop** [comment]
I believe this should be addressed via: https://github.com/dougmoscrop/serverless-http/pull/42/files

**Comment by dougmoscrop** [comment]
I've continued to work on this, but baseUrl is not actually a valid property of the request object. It's an express-only construct that you should define when setting up your application, so I don't think this is applicable to all users.

**Pull request closed without merging**
