### PR TITLE
If a header's value is an array, convert it to csv to make API Gatewa…

### PR DESCRIPTION
**Pull request by bdgamble**
…y accept the response

Add real-world test where koa-router does this and it breaks api-gateway

### CODE REVIEW

**Comment by bdgamble** [comment]
@dougmoscrop

**Comment by dougmoscrop** [comment]
`join(', ')` (with space after comma) maybe? seems more like what docs show everywheree

**Comment by panva** [comment]
You can actually work your way around the 1 unique header limitation > see https://github.com/awslabs/aws-serverless-express/pull/41

**Comment by dougmoscrop** [comment]
@panva interesting, thanks for the tip. this isn't the same issue per se (this is the case where the header itself supports comma separated values, but in code it is set as an array and not serialized correctly to APIG)

just to be clear this is the problem (some koa library does this):

`addHeader('Allow', ['GET', 'PUT'])`

not:

`addHeader('Allow', 'GET')`
`addHeader('Allow', 'PUT')`

**Comment by panva** [comment]
overcoming some koa library should really come lower in priority than, i.e. being able to send more than one cookie :)

**Comment by dougmoscrop** [comment]
I created an issue for it. This code is already written and fixes a real
world bug we have.

**Pull request merged**
